//! Built-in quick-action catalog, extracted verbatim from search.rs.

pub(crate) struct QuickAction {
    pub(crate) triggers: &'static [&'static str],
    pub(crate) name: &'static str,
    pub(crate) breadcrumb: &'static str,
    pub(crate) launch_command: &'static str,
    pub(crate) description: &'static str,
}

pub(crate) static QUICK_ACTIONS: &[QuickAction] = &[
    QuickAction {
        triggers: &[
            "theme darker",
            "switch to darker",
            "darker theme",
            "dark mode",
        ],
        name: "Switch Theme: Darker",
        breadcrumb: "Theme Switcher > Darker",
        launch_command: "action:switch_theme:darker",
        description: "Switch launcher theme to Darker.",
    },
    QuickAction {
        triggers: &["theme nord", "switch to nord", "nord theme", "nord darker"],
        name: "Switch Theme: Nord Darker",
        breadcrumb: "Theme Switcher > Nord Darker",
        launch_command: "action:switch_theme:nord",
        description: "Switch launcher theme to Nord Darker.",
    },
    QuickAction {
        triggers: &[
            "theme light",
            "switch to light",
            "light theme",
            "light mode",
        ],
        name: "Switch Theme: Light",
        breadcrumb: "Theme Switcher > Light",
        launch_command: "action:switch_theme:light",
        description: "Switch launcher theme to Light.",
    },
    QuickAction {
        triggers: &[
            "settings",
            "preferences",
            "options",
            "general",
            "advanced",
            "shortcuts",
            "launcher settings",
        ],
        name: "Open Settings",
        breadcrumb: "Settings & Management > Open Settings",
        launch_command: "action:open_settings",
        description: "Open settings folder to edit index.db or configs manually.",
    },
    QuickAction {
        triggers: &["about", "copy version"],
        name: "About / Copy Version",
        breadcrumb: "Settings & Management > About",
        launch_command: "action:copy_version",
        description: "Copy app version to clipboard.",
    },
    QuickAction {
        triggers: &[
            "account",
            "organizations",
            "cloud sync",
            "affiliate dashboard",
        ],
        name: "Account & Sync",
        breadcrumb: "Settings & Management > Account",
        launch_command: "https://github.com/PranshulSoni/Project-Raycast",
        description: "Manage account and sync settings online.",
    },
    QuickAction {
        triggers: &["changelog", "what's new"],
        name: "Changelog",
        breadcrumb: "Settings & Management > Changelog",
        launch_command: "https://github.com/PranshulSoni/Project-Raycast/commits/main",
        description: "View recent changes on GitHub.",
    },
    QuickAction {
        triggers: &[
            "check for app updates",
            "update app",
            "check for extension updates",
        ],
        name: "Check for App Updates",
        breadcrumb: "Settings & Management > Check for Updates",
        launch_command: "https://github.com/PranshulSoni/Project-Raycast",
        description: "Check GitHub repository for new launcher releases.",
    },
    QuickAction {
        triggers: &["check for updates", "windows update"],
        name: "Windows Update",
        breadcrumb: "System > Settings > Windows Update",
        launch_command: "ms-settings:windowsupdate",
        description: "Open Windows Update settings.",
    },
    QuickAction {
        triggers: &[
            "search",
            "search settings",
            "windows search",
            "search permissions",
            "safe search",
            "cloud content search",
            "search history",
        ],
        name: "Windows Search Settings",
        breadcrumb: "Settings > Privacy & Security > Search Permissions",
        launch_command: "ms-settings:search-permissions",
        description:
            "Configure Windows Search permissions, SafeSearch, cloud content, and history.",
    },
    QuickAction {
        triggers: &[
            "search indexing",
            "indexing",
            "indexing options",
            "indexed locations",
            "windows indexing",
            "search index",
            "rebuild search index",
        ],
        name: "Indexing Options",
        breadcrumb: "Control Panel > Indexing Options",
        launch_command: "control.exe /name Microsoft.IndexingOptions",
        description: "Configure indexed locations and rebuild the Windows Search index.",
    },
    QuickAction {
        triggers: &[
            "find my files",
            "search files settings",
            "enhanced search",
            "classic search",
            "file search settings",
        ],
        name: "Searching Windows",
        breadcrumb: "Settings > Privacy & Security > Searching Windows",
        launch_command: "ms-settings:cortana-windowssearch",
        description: "Control classic/enhanced Windows file search and excluded folders.",
    },
    QuickAction {
        triggers: &["copy logs", "show logs", "reveal logs"],
        name: "Copy / Reveal Logs",
        breadcrumb: "Settings & Management > Copy Logs",
        launch_command: "action:copy_logs",
        description: "Copy log file contents to clipboard.",
    },
    QuickAction {
        triggers: &[
            "export settings",
            "import settings",
            "export data",
            "import data",
        ],
        name: "Export / Import Data",
        breadcrumb: "Settings & Management > Data",
        launch_command: "action:open_settings",
        description: "Open settings folder to backup or restore index.db manually.",
    },
    QuickAction {
        triggers: &["open manual", "help", "documentation", "show onboarding"],
        name: "Open Manual",
        breadcrumb: "Settings & Management > Manual",
        launch_command: "https://github.com/PranshulSoni/Project-Raycast#readme",
        description: "Open documentation and onboarding guide.",
    },
    QuickAction {
        triggers: &["store", "share"],
        name: "Store & Share",
        breadcrumb: "Settings & Management > Store",
        launch_command: "https://github.com/PranshulSoni/Project-Raycast",
        description: "Visit the extension store or share the app.",
    },
    QuickAction {
        triggers: &["quick look"],
        name: "Quick Look",
        breadcrumb: "Settings & Management > Quick Look",
        launch_command: "action:quick_look",
        description: "Preview selected file (simulated).",
    },
    QuickAction {
        triggers: &["set volume to 0%", "mute"],
        name: "Set Volume to 0%",
        breadcrumb: "System > Volume > 0%",
        launch_command: "action:volume:0",
        description: "Mute volume.",
    },
    QuickAction {
        triggers: &["set volume to 25%"],
        name: "Set Volume to 25%",
        breadcrumb: "System > Volume > 25%",
        launch_command: "action:volume:25",
        description: "Set volume to 25%.",
    },
    QuickAction {
        triggers: &["set volume to 50%"],
        name: "Set Volume to 50%",
        breadcrumb: "System > Volume > 50%",
        launch_command: "action:volume:50",
        description: "Set volume to 50%.",
    },
    QuickAction {
        triggers: &["set volume to 75%"],
        name: "Set Volume to 75%",
        breadcrumb: "System > Volume > 75%",
        launch_command: "action:volume:75",
        description: "Set volume to 75%.",
    },
    QuickAction {
        triggers: &["set volume to 100%", "max volume"],
        name: "Set Volume to 100%",
        breadcrumb: "System > Volume > 100%",
        launch_command: "action:volume:100",
        description: "Set volume to 100%.",
    },
    QuickAction {
        triggers: &[
            "toggle theme",
            "dark mode",
            "light mode",
            "toggle system appearance",
        ],
        name: "Toggle System Appearance",
        breadcrumb: "System > Personalization > Toggle Theme",
        launch_command: "action:toggle_theme",
        description: "Toggle Windows between Dark and Light mode.",
    },
    QuickAction {
        triggers: &["quit all apps"],
        name: "Quit All Apps",
        breadcrumb: "System > Quit All Apps",
        launch_command: "action:quit_all_apps",
        description: "Close all running applications.",
    },
    QuickAction {
        triggers: &["quit all apps except frontmost", "quit other apps"],
        name: "Quit All Apps Except Frontmost",
        breadcrumb: "System > Quit Other Apps",
        launch_command: "action:quit_other_apps",
        description: "Close all applications except the active one.",
    },
    QuickAction {
        triggers: &["hide all apps except frontmost", "hide other apps"],
        name: "Hide All Apps Except Frontmost",
        breadcrumb: "System > Hide Other Apps",
        launch_command: "action:hide_other_apps",
        description: "Minimize all windows except the active one.",
    },
    QuickAction {
        triggers: &["toggle hdr"],
        name: "Toggle HDR",
        breadcrumb: "System > Display > Toggle HDR",
        launch_command: "action:toggle_hdr",
        description: "Toggle HDR on/off via Win+Alt+B.",
    },
    QuickAction {
        triggers: &["move to desktop 1", "move to virtual desktop 1"],
        name: "Move to Desktop 1",
        breadcrumb: "Window Management > Move to Desktop 1",
        launch_command: "action:window:move_desktop_1",
        description: "Move the active window to virtual desktop 1.",
    },
    QuickAction {
        triggers: &["move to desktop 2", "move to virtual desktop 2"],
        name: "Move to Desktop 2",
        breadcrumb: "Window Management > Move to Desktop 2",
        launch_command: "action:window:move_desktop_2",
        description: "Move the active window to virtual desktop 2.",
    },
    QuickAction {
        triggers: &["move to desktop 3", "move to virtual desktop 3"],
        name: "Move to Desktop 3",
        breadcrumb: "Window Management > Move to Desktop 3",
        launch_command: "action:window:move_desktop_3",
        description: "Move the active window to virtual desktop 3.",
    },
    QuickAction {
        triggers: &["move to desktop 4", "move to virtual desktop 4"],
        name: "Move to Desktop 4",
        breadcrumb: "Window Management > Move to Desktop 4",
        launch_command: "action:window:move_desktop_4",
        description: "Move the active window to virtual desktop 4.",
    },
    QuickAction {
        triggers: &["move to desktop 5", "move to virtual desktop 5"],
        name: "Move to Desktop 5",
        breadcrumb: "Window Management > Move to Desktop 5",
        launch_command: "action:window:move_desktop_5",
        description: "Move the active window to virtual desktop 5.",
    },
    QuickAction {
        triggers: &["move to desktop 6", "move to virtual desktop 6"],
        name: "Move to Desktop 6",
        breadcrumb: "Window Management > Move to Desktop 6",
        launch_command: "action:window:move_desktop_6",
        description: "Move the active window to virtual desktop 6.",
    },
    QuickAction {
        triggers: &["move to desktop 7", "move to virtual desktop 7"],
        name: "Move to Desktop 7",
        breadcrumb: "Window Management > Move to Desktop 7",
        launch_command: "action:window:move_desktop_7",
        description: "Move the active window to virtual desktop 7.",
    },
    QuickAction {
        triggers: &["move to desktop 8", "move to virtual desktop 8"],
        name: "Move to Desktop 8",
        breadcrumb: "Window Management > Move to Desktop 8",
        launch_command: "action:window:move_desktop_8",
        description: "Move the active window to virtual desktop 8.",
    },
    QuickAction {
        triggers: &["move to desktop 9", "move to virtual desktop 9"],
        name: "Move to Desktop 9",
        breadcrumb: "Window Management > Move to Desktop 9",
        launch_command: "action:window:move_desktop_9",
        description: "Move the active window to virtual desktop 9.",
    },
    QuickAction {
        triggers: &["move to desktop 10", "move to virtual desktop 10"],
        name: "Move to Desktop 10",
        breadcrumb: "Window Management > Move to Desktop 10",
        launch_command: "action:window:move_desktop_10",
        description: "Move the active window to virtual desktop 10.",
    },
    QuickAction {
        triggers: &["open desktop 1", "switch to desktop 1", "go to desktop 1"],
        name: "Open Desktop 1",
        breadcrumb: "Window Management > Open Desktop 1",
        launch_command: "action:window:open_desktop_1",
        description: "Switch to virtual desktop 1.",
    },
    QuickAction {
        triggers: &["open desktop 2", "switch to desktop 2", "go to desktop 2"],
        name: "Open Desktop 2",
        breadcrumb: "Window Management > Open Desktop 2",
        launch_command: "action:window:open_desktop_2",
        description: "Switch to virtual desktop 2.",
    },
    QuickAction {
        triggers: &["open desktop 3", "switch to desktop 3", "go to desktop 3"],
        name: "Open Desktop 3",
        breadcrumb: "Window Management > Open Desktop 3",
        launch_command: "action:window:open_desktop_3",
        description: "Switch to virtual desktop 3.",
    },
    QuickAction {
        triggers: &["open desktop 4", "switch to desktop 4", "go to desktop 4"],
        name: "Open Desktop 4",
        breadcrumb: "Window Management > Open Desktop 4",
        launch_command: "action:window:open_desktop_4",
        description: "Switch to virtual desktop 4.",
    },
    QuickAction {
        triggers: &["open desktop 5", "switch to desktop 5", "go to desktop 5"],
        name: "Open Desktop 5",
        breadcrumb: "Window Management > Open Desktop 5",
        launch_command: "action:window:open_desktop_5",
        description: "Switch to virtual desktop 5.",
    },
    QuickAction {
        triggers: &["open desktop 6", "switch to desktop 6", "go to desktop 6"],
        name: "Open Desktop 6",
        breadcrumb: "Window Management > Open Desktop 6",
        launch_command: "action:window:open_desktop_6",
        description: "Switch to virtual desktop 6.",
    },
    QuickAction {
        triggers: &["open desktop 7", "switch to desktop 7", "go to desktop 7"],
        name: "Open Desktop 7",
        breadcrumb: "Window Management > Open Desktop 7",
        launch_command: "action:window:open_desktop_7",
        description: "Switch to virtual desktop 7.",
    },
    QuickAction {
        triggers: &["open desktop 8", "switch to desktop 8", "go to desktop 8"],
        name: "Open Desktop 8",
        breadcrumb: "Window Management > Open Desktop 8",
        launch_command: "action:window:open_desktop_8",
        description: "Switch to virtual desktop 8.",
    },
    QuickAction {
        triggers: &["open desktop 9", "switch to desktop 9", "go to desktop 9"],
        name: "Open Desktop 9",
        breadcrumb: "Window Management > Open Desktop 9",
        launch_command: "action:window:open_desktop_9",
        description: "Switch to virtual desktop 9.",
    },
    QuickAction {
        triggers: &[
            "open desktop 10",
            "switch to desktop 10",
            "go to desktop 10",
        ],
        name: "Open Desktop 10",
        breadcrumb: "Window Management > Open Desktop 10",
        launch_command: "action:window:open_desktop_10",
        description: "Switch to virtual desktop 10.",
    },
    QuickAction {
        triggers: &["close desktop", "close virtual desktop"],
        name: "Close Desktop",
        breadcrumb: "Window Management > Close Desktop",
        launch_command: "action:window:close_desktop",
        description: "Close the current virtual desktop.",
    },
    QuickAction {
        triggers: &["close desktop active", "close active desktop"],
        name: "Close Desktop Active",
        breadcrumb: "Window Management > Close Desktop Active",
        launch_command: "action:window:close_desktop_active",
        description: "Close the current virtual desktop and move windows.",
    },
    QuickAction {
        triggers: &["rename desktop", "rename virtual desktop"],
        name: "Rename Desktop",
        breadcrumb: "Window Management > Rename Desktop",
        launch_command: "action:window:rename_desktop",
        description: "Rename the current virtual desktop.",
    },
    QuickAction {
        triggers: &["move to next desktop", "move to next virtual desktop"],
        name: "Move to Next Desktop",
        breadcrumb: "Window Management > Move to Next Desktop",
        launch_command: "action:window:move_next_desktop",
        description: "Move the active window to the next virtual desktop.",
    },
    QuickAction {
        triggers: &[
            "move to previous desktop",
            "move to previous virtual desktop",
        ],
        name: "Move to Previous Desktop",
        breadcrumb: "Window Management > Move to Previous Desktop",
        launch_command: "action:window:move_previous_desktop",
        description: "Move the active window to the previous virtual desktop.",
    },
    QuickAction {
        triggers: &["move to next display", "move to next monitor"],
        name: "Move to Next Display",
        breadcrumb: "Window Management > Move to Next Display",
        launch_command: "action:window:move_next_display",
        description: "Move the active window to the next display (monitor).",
    },
    QuickAction {
        triggers: &["move to previous display", "move to previous monitor"],
        name: "Move to Previous Display",
        breadcrumb: "Window Management > Move to Previous Display",
        launch_command: "action:window:move_previous_display",
        description: "Move the active window to the previous display (monitor).",
    },
    QuickAction {
        triggers: &["paste sequentially", "paste sequence"],
        name: "Paste Sequentially",
        breadcrumb: "Clipboard > Paste Sequentially",
        launch_command: "action:clipboard:paste_sequentially",
        description: "Paste multiple items from clipboard history in sequence.",
    },
    QuickAction {
        triggers: &["lock", "lock screen", "lock pc", "lock computer"],
        name: "Lock Screen",
        breadcrumb: "System > Security > Lock this PC immediately",
        launch_command: "action:lock",
        description: "Lock the screen immediately.",
    },
    QuickAction {
        triggers: &[
            "shutdown",
            "shut down",
            "power off",
            "turn off computer",
            "turn off pc",
        ],
        name: "Shut Down",
        breadcrumb: "System > Power > Shut down this computer",
        launch_command: "action:shutdown",
        description: "Shut down the computer.",
    },
    QuickAction {
        triggers: &["restart", "reboot", "restart computer", "restart pc"],
        name: "Restart",
        breadcrumb: "System > Power > Restart this computer",
        launch_command: "action:restart",
        description: "Restart the computer.",
    },
    QuickAction {
        triggers: &["sleep", "sleep computer", "sleep pc"],
        name: "Sleep",
        breadcrumb: "System > Power > Put computer to sleep",
        launch_command: "action:sleep",
        description: "Put the computer to sleep.",
    },
    QuickAction {
        triggers: &["hibernate", "hibernate computer", "hibernate pc"],
        name: "Hibernate",
        breadcrumb: "System > Power > Hibernate this computer",
        launch_command: "action:hibernate",
        description: "Hibernate the computer.",
    },
    QuickAction {
        triggers: &["log out", "logout", "sign out", "sign out user"],
        name: "Log Out",
        breadcrumb: "System > Account > Sign out",
        launch_command: "action:logout",
        description: "Sign out of Windows.",
    },
    QuickAction {
        triggers: &[
            "sleep displays",
            "turn off displays",
            "turn off monitor",
            "screen off",
        ],
        name: "Sleep Displays",
        breadcrumb: "System > Power > Turn displays off",
        launch_command: "action:sleep_displays",
        description: "Turn off the connected displays without sleeping the PC.",
    },
    QuickAction {
        triggers: &["show screen saver", "screensaver", "start screensaver"],
        name: "Show Screen Saver",
        breadcrumb: "System > Display > Screen saver",
        launch_command: "action:show_screensaver",
        description: "Start the Windows screen saver.",
    },
    QuickAction {
        triggers: &["clipboard history", "show clipboard", "clipboard"],
        name: "Clipboard History",
        breadcrumb: "Clipboard > History",
        launch_command: "query:clip:",
        description: "Open clipboard history inside the launcher.",
    },
    QuickAction {
        triggers: &[
            "paste latest screenshot",
            "paste screenshot",
            "latest screenshot",
        ],
        name: "Paste Latest Screenshot",
        breadcrumb: "Screenshots > Paste latest screenshot",
        launch_command: "action:paste_latest_screenshot",
        description: "Paste the newest screenshot from Clipboard History.",
    },
    QuickAction {
        triggers: &[
            "reset window position",
            "reset launcher window",
            "center launcher",
        ],
        name: "Reset Window Position",
        breadcrumb: "Settings > Launcher > Reset window position",
        launch_command: "action:reset_window_position",
        description: "Reset the launcher to the active monitor.",
    },
    QuickAction {
        triggers: &["reveal logs", "open logs", "logs folder"],
        name: "Reveal Logs",
        breadcrumb: "Settings > Logs > Reveal logs",
        launch_command: "action:reveal_logs",
        description: "Open the app data folder containing logs.",
    },
    QuickAction {
        triggers: &["show desktop", "peek desktop", "minimize all", "desktop"],
        name: "Show Desktop",
        breadcrumb: "Windows > Desktop > Show desktop",
        launch_command: "action:show_desktop",
        description: "Toggle the desktop view.",
    },
    QuickAction {
        triggers: &["run", "open run", "run dialog", "windows run"],
        name: "Open Run",
        breadcrumb: "Windows > Run dialog",
        launch_command: "action:open_run",
        description: "Open the Windows Run dialog.",
    },
    QuickAction {
        triggers: &[
            "quit active app",
            "close active app",
            "close current window",
            "close foreground window",
        ],
        name: "Quit Active App",
        breadcrumb: "Windows > Active app > Close",
        launch_command: "action:quit_active_app",
        description: "Ask the previously active app window to close.",
    },
    QuickAction {
        triggers: &[
            "empty recycle bin",
            "clear recycle bin",
            "empty trash",
            "recycle bin",
        ],
        name: "Empty Recycle Bin",
        breadcrumb: "System > Storage > Empty the Recycle Bin",
        launch_command: "action:recycle",
        description: "Permanently delete all items in the Recycle Bin.",
    },
    QuickAction {
        triggers: &[
            "open recycle bin",
            "recycle bin folder",
            "open trash",
            "trash folder",
        ],
        name: "Open Recycle Bin",
        breadcrumb: "File System > Recycle Bin",
        launch_command: "action:open_recycle_bin",
        description: "Open the Recycle Bin folder.",
    },
    QuickAction {
        triggers: &["open downloads", "downloads folder", "my downloads"],
        name: "Open Downloads",
        breadcrumb: "File System > User > Downloads",
        launch_command: "action:folder:downloads",
        description: "Open the Downloads folder.",
    },
    QuickAction {
        triggers: &["open desktop", "desktop folder", "go to desktop"],
        name: "Open Desktop",
        breadcrumb: "File System > User > Desktop",
        launch_command: "action:folder:desktop",
        description: "Open the Desktop folder.",
    },
    QuickAction {
        triggers: &["open documents", "documents folder", "my documents"],
        name: "Open Documents",
        breadcrumb: "File System > User > Documents",
        launch_command: "action:folder:documents",
        description: "Open the Documents folder.",
    },
    QuickAction {
        triggers: &[
            "open pictures",
            "pictures folder",
            "my pictures",
            "photos folder",
        ],
        name: "Open Pictures",
        breadcrumb: "File System > User > Pictures",
        launch_command: "action:folder:pictures",
        description: "Open the Pictures folder.",
    },
    QuickAction {
        triggers: &["open music", "music folder", "my music"],
        name: "Open Music",
        breadcrumb: "File System > User > Music",
        launch_command: "action:folder:music",
        description: "Open the Music folder.",
    },
    QuickAction {
        triggers: &["open videos", "videos folder", "my videos"],
        name: "Open Videos",
        breadcrumb: "File System > User > Videos",
        launch_command: "action:folder:videos",
        description: "Open the Videos folder.",
    },
    QuickAction {
        triggers: &["open temp", "temp folder", "temporary files", "open tmp"],
        name: "Open Temp Folder",
        breadcrumb: "System > Temp > %TEMP% folder",
        launch_command: "action:folder:temp",
        description: "Open the Windows temporary files folder.",
    },
    QuickAction {
        triggers: &["open startup", "startup folder", "startup programs folder"],
        name: "Open Startup Folder",
        breadcrumb: "System > Startup > Shell startup programs",
        launch_command: "shell:startup",
        description: "Open the user startup programs folder.",
    },
    QuickAction {
        triggers: &["flush dns", "clear dns", "reset dns", "dns cache"],
        name: "Flush DNS Cache",
        breadcrumb: "Network > DNS > Flush resolver cache",
        launch_command: "action:flushdns",
        description: "Clear the DNS resolver cache.",
    },
    QuickAction {
        triggers: &["open task manager", "task manager", "taskmgr"],
        name: "Open Task Manager",
        breadcrumb: "System > Performance > Task Manager",
        launch_command: "taskmgr.exe",
        description: "Open Task Manager.",
    },
    QuickAction {
        triggers: &["open registry", "registry editor", "regedit"],
        name: "Open Registry Editor",
        breadcrumb: "System > Advanced > Registry Editor",
        launch_command: "regedit.exe",
        description: "Open the Windows Registry Editor.",
    },
    QuickAction {
        triggers: &[
            "open environment variables",
            "environment variables",
            "env variables",
            "path variable",
        ],
        name: "Environment Variables",
        breadcrumb: "System > Advanced System Settings > Environment Variables",
        launch_command: "action:envvars",
        description: "Open Environment Variables settings.",
    },
    QuickAction {
        triggers: &["clear clipboard", "empty clipboard", "reset clipboard"],
        name: "Clear Clipboard",
        breadcrumb: "System > Clipboard > Clear clipboard contents",
        launch_command: "action:clearclip",
        description: "Clear all contents from the clipboard.",
    },
    QuickAction {
        triggers: &["open hosts file", "hosts file", "edit hosts"],
        name: "Open Hosts File",
        breadcrumb: "Network > DNS > Edit hosts file",
        launch_command: "action:hosts",
        description: "Open the system hosts file in Notepad.",
    },
    // ── Windows Settings ────────────────────────────────────────────────────
    QuickAction {
        triggers: &[
            "wifi",
            "wifi settings",
            "wireless",
            "network settings",
            "connect wifi",
        ],
        name: "Wi-Fi Settings",
        breadcrumb: "Settings > Network & Internet > Wi-Fi",
        launch_command: "ms-settings:network-wifi",
        description: "Manage Wi-Fi connections.",
    },
    QuickAction {
        triggers: &[
            "bluetooth",
            "bluetooth settings",
            "pair device",
            "bluetooth devices",
        ],
        name: "Bluetooth Settings",
        breadcrumb: "Settings > Bluetooth & Devices",
        launch_command: "ms-settings:bluetooth",
        description: "Pair and manage Bluetooth devices.",
    },
    QuickAction {
        triggers: &[
            "display settings",
            "screen resolution",
            "resolution",
            "display",
            "monitor",
            "brightness",
        ],
        name: "Display Settings",
        breadcrumb: "Settings > System > Display",
        launch_command: "ms-settings:display",
        description: "Change display resolution, brightness and orientation.",
    },
    QuickAction {
        triggers: &["night light", "blue light", "night mode", "warm colors"],
        name: "Night Light",
        breadcrumb: "Settings > System > Display > Night Light",
        launch_command: "ms-settings:nightlight",
        description: "Reduce blue light with Night Light.",
    },
    QuickAction {
        triggers: &[
            "sound settings",
            "audio settings",
            "volume settings",
            "sound output",
            "speaker",
            "microphone",
        ],
        name: "Sound Settings",
        breadcrumb: "Settings > System > Sound",
        launch_command: "ms-settings:sound",
        description: "Manage audio output and input devices.",
    },
    QuickAction {
        triggers: &[
            "notifications",
            "notification settings",
            "do not disturb",
            "focus assist",
            "app notifications",
        ],
        name: "Notification Settings",
        breadcrumb: "Settings > System > Notifications",
        launch_command: "ms-settings:notifications",
        description: "Control app notifications and Do Not Disturb.",
    },
    QuickAction {
        triggers: &[
            "power settings",
            "battery settings",
            "sleep settings",
            "power plan",
            "battery saver",
        ],
        name: "Power & Battery Settings",
        breadcrumb: "Settings > System > Power & Battery",
        launch_command: "ms-settings:powersleep",
        description: "Configure power plan and battery saver.",
    },
    QuickAction {
        triggers: &[
            "apps settings",
            "installed apps",
            "uninstall app",
            "remove app",
            "add remove programs",
        ],
        name: "Installed Apps",
        breadcrumb: "Settings > Apps > Installed Apps",
        launch_command: "ms-settings:appsfeatures",
        description: "View, modify or uninstall installed apps.",
    },
    QuickAction {
        triggers: &[
            "default apps",
            "default browser",
            "set default",
            "default programs",
        ],
        name: "Default Apps",
        breadcrumb: "Settings > Apps > Default Apps",
        launch_command: "ms-settings:defaultapps",
        description: "Set default apps for file types and protocols.",
    },
    QuickAction {
        triggers: &[
            "startup apps",
            "startup programs",
            "autostart",
            "apps on startup",
        ],
        name: "Startup Apps",
        breadcrumb: "Settings > Apps > Startup",
        launch_command: "ms-settings:startupapps",
        description: "Control which apps launch on startup.",
    },
    QuickAction {
        triggers: &[
            "accounts",
            "account settings",
            "your info",
            "microsoft account",
            "user account",
        ],
        name: "Your Account",
        breadcrumb: "Settings > Accounts > Your Info",
        launch_command: "ms-settings:yourinfo",
        description: "View your Microsoft account info.",
    },
    QuickAction {
        triggers: &[
            "sign in options",
            "pin",
            "windows hello",
            "fingerprint",
            "face recognition",
            "password settings",
        ],
        name: "Sign-In Options",
        breadcrumb: "Settings > Accounts > Sign-In Options",
        launch_command: "ms-settings:signinoptions",
        description: "Manage PIN, password and Windows Hello.",
    },
    QuickAction {
        triggers: &["vpn", "vpn settings", "virtual private network"],
        name: "VPN Settings",
        breadcrumb: "Settings > Network & Internet > VPN",
        launch_command: "ms-settings:network-vpn",
        description: "Configure VPN connections.",
    },
    QuickAction {
        triggers: &["proxy settings", "proxy", "network proxy"],
        name: "Proxy Settings",
        breadcrumb: "Settings > Network & Internet > Proxy",
        launch_command: "ms-settings:network-proxy",
        description: "Configure proxy for network connections.",
    },
    QuickAction {
        triggers: &[
            "windows update",
            "check updates",
            "update windows",
            "updates",
        ],
        name: "Windows Update",
        breadcrumb: "Settings > Windows Update",
        launch_command: "ms-settings:windowsupdate",
        description: "Check for and install Windows updates.",
    },
    QuickAction {
        triggers: &[
            "storage settings",
            "disk space",
            "storage",
            "storage sense",
            "free up space",
        ],
        name: "Storage Settings",
        breadcrumb: "Settings > System > Storage",
        launch_command: "ms-settings:storagesense",
        description: "Manage disk storage and Storage Sense.",
    },
    QuickAction {
        triggers: &[
            "privacy settings",
            "privacy",
            "location",
            "camera access",
            "microphone access",
            "app permissions",
        ],
        name: "Privacy Settings",
        breadcrumb: "Settings > Privacy & Security",
        launch_command: "ms-settings:privacy",
        description: "Control privacy and app permissions.",
    },
    QuickAction {
        triggers: &["location settings", "location access", "location privacy"],
        name: "Location Settings",
        breadcrumb: "Settings > Privacy & Security > Location",
        launch_command: "ms-settings:privacy-location",
        description: "Control which apps can access your location.",
    },
    QuickAction {
        triggers: &["camera settings", "camera access", "camera privacy"],
        name: "Camera Settings",
        breadcrumb: "Settings > Privacy & Security > Camera",
        launch_command: "ms-settings:privacy-webcam",
        description: "Control which apps can access your camera.",
    },
    QuickAction {
        triggers: &[
            "date time settings",
            "date and time",
            "clock settings",
            "time zone",
            "set time",
        ],
        name: "Date & Time Settings",
        breadcrumb: "Settings > Time & Language > Date & Time",
        launch_command: "ms-settings:dateandtime",
        description: "Set date, time and time zone.",
    },
    QuickAction {
        triggers: &[
            "language settings",
            "region settings",
            "keyboard language",
            "input language",
            "add language",
        ],
        name: "Language & Region",
        breadcrumb: "Settings > Time & Language > Language & Region",
        launch_command: "ms-settings:regionlanguage",
        description: "Add or change display and input language.",
    },
    QuickAction {
        triggers: &[
            "mouse settings",
            "pointer speed",
            "scroll speed",
            "mouse buttons",
        ],
        name: "Mouse Settings",
        breadcrumb: "Settings > Bluetooth & Devices > Mouse",
        launch_command: "ms-settings:mousetouchpad",
        description: "Configure mouse pointer and scroll settings.",
    },
    QuickAction {
        triggers: &[
            "touchpad settings",
            "trackpad",
            "gestures",
            "touchpad sensitivity",
        ],
        name: "Touchpad Settings",
        breadcrumb: "Settings > Bluetooth & Devices > Touchpad",
        launch_command: "ms-settings:devices-touchpad",
        description: "Configure touchpad gestures and sensitivity.",
    },
    QuickAction {
        triggers: &[
            "personalization",
            "wallpaper",
            "desktop background",
            "theme",
            "dark mode",
            "light mode",
            "colors",
        ],
        name: "Personalization",
        breadcrumb: "Settings > Personalization",
        launch_command: "ms-settings:personalization",
        description: "Change wallpaper, theme, colors and lock screen.",
    },
    QuickAction {
        triggers: &["taskbar settings", "taskbar", "taskbar icons"],
        name: "Taskbar Settings",
        breadcrumb: "Settings > Personalization > Taskbar",
        launch_command: "ms-settings:taskbar",
        description: "Customize the taskbar.",
    },
    QuickAction {
        triggers: &[
            "accessibility",
            "ease of access",
            "narrator",
            "magnifier",
            "high contrast",
            "color filters",
        ],
        name: "Accessibility Settings",
        breadcrumb: "Settings > Accessibility",
        launch_command: "ms-settings:easeofaccess-display",
        description: "Accessibility features like Narrator, Magnifier.",
    },
    QuickAction {
        triggers: &["developer mode", "developer settings", "sideload"],
        name: "Developer Settings",
        breadcrumb: "Settings > System > For Developers",
        launch_command: "ms-settings:developers",
        description: "Enable developer mode and sideloading.",
    },
    QuickAction {
        triggers: &[
            "activate windows",
            "windows activation",
            "product key",
            "license",
        ],
        name: "Windows Activation",
        breadcrumb: "Settings > System > Activation",
        launch_command: "ms-settings:activation",
        description: "Check or change Windows activation.",
    },
    // ── System Control Actions ───────────────────────────────────────────────
    QuickAction {
        triggers: &[
            "restart explorer",
            "restart explorer.exe",
            "restart file explorer",
            "restart taskbar",
            "explorer restart",
        ],
        name: "Restart Explorer",
        breadcrumb: "System > Process > Restart Windows Explorer",
        launch_command: "action:restart_explorer",
        description: "Kill and restart Windows Explorer (shell).",
    },
    QuickAction {
        triggers: &[
            "volume up",
            "increase volume",
            "louder",
            "turn up volume",
            "volume increase",
        ],
        name: "Volume Up",
        breadcrumb: "System > Audio > Increase master volume",
        launch_command: "action:volume_up",
        description: "Increase master volume by 10%.",
    },
    QuickAction {
        triggers: &[
            "volume down",
            "decrease volume",
            "quieter",
            "turn down volume",
            "volume decrease",
            "lower volume",
        ],
        name: "Volume Down",
        breadcrumb: "System > Audio > Decrease master volume",
        launch_command: "action:volume_down",
        description: "Decrease master volume by 10%.",
    },
    QuickAction {
        triggers: &[
            "mute",
            "unmute",
            "toggle mute",
            "mute volume",
            "silence",
            "toggle volume",
        ],
        name: "Toggle Mute",
        breadcrumb: "System > Audio > Toggle mute/unmute",
        launch_command: "action:toggle_mute",
        description: "Toggle master audio mute on/off.",
    },
    QuickAction {
        triggers: &[
            "toggle bluetooth",
            "bluetooth on",
            "bluetooth off",
            "turn on bluetooth",
            "turn off bluetooth",
            "bt toggle",
        ],
        name: "Toggle Bluetooth",
        breadcrumb: "System > Bluetooth > Toggle on/off",
        launch_command: "action:toggle_bluetooth",
        description: "Toggle Bluetooth radio on or off.",
    },
    QuickAction {
        triggers: &[
            "toggle wifi",
            "wifi on",
            "wifi off",
            "turn on wifi",
            "turn off wifi",
            "airplane mode",
            "toggle wireless",
        ],
        name: "Toggle Wi-Fi",
        breadcrumb: "System > Network > Toggle Wi-Fi on/off",
        launch_command: "action:toggle_wifi",
        description: "Toggle Wi-Fi radio on or off.",
    },
    QuickAction {
        triggers: &[
            "ip config",
            "ip address",
            "my ip",
            "show ip",
            "ipconfig",
            "network info",
        ],
        name: "Show IP Configuration",
        breadcrumb: "Network > IP > Show IP configuration",
        launch_command: "action:ipconfig",
        description: "Show IP address and network configuration.",
    },
    QuickAction {
        triggers: &["release ip", "ip release", "dhcp release"],
        name: "Release IP Address",
        breadcrumb: "Network > IP > Release DHCP lease",
        launch_command: "action:ip_release",
        description: "Release the current DHCP IP address.",
    },
    QuickAction {
        triggers: &["renew ip", "ip renew", "dhcp renew", "renew ip address"],
        name: "Renew IP Address",
        breadcrumb: "Network > IP > Renew DHCP lease",
        launch_command: "action:ip_renew",
        description: "Renew the DHCP IP address.",
    },
    QuickAction {
        triggers: &[
            "event viewer",
            "event log",
            "events",
            "view events",
            "windows logs",
        ],
        name: "Event Viewer",
        breadcrumb: "System > Diagnostics > Event Viewer",
        launch_command: "eventvwr.msc",
        description: "Open Windows Event Viewer.",
    },
    QuickAction {
        triggers: &[
            "device manager",
            "devices",
            "hardware",
            "driver manager",
            "device settings",
        ],
        name: "Device Manager",
        breadcrumb: "System > Hardware > Device Manager",
        launch_command: "devmgmt.msc",
        description: "View and manage hardware devices and drivers.",
    },
    QuickAction {
        triggers: &[
            "services",
            "services manager",
            "windows services",
            "service manager",
            "start service",
            "stop service",
        ],
        name: "Services Manager",
        breadcrumb: "System > Services > Windows Services",
        launch_command: "services.msc",
        description: "Start, stop or configure Windows services.",
    },
    QuickAction {
        triggers: &[
            "disk cleanup",
            "clean disk",
            "free up disk",
            "disk cleanup tool",
            "cleanup",
        ],
        name: "Disk Cleanup",
        breadcrumb: "System > Storage > Disk Cleanup",
        launch_command: "cleanmgr.exe",
        description: "Free up disk space by removing temporary files.",
    },
    QuickAction {
        triggers: &[
            "group policy",
            "gpedit",
            "group policy editor",
            "local group policy",
        ],
        name: "Group Policy Editor",
        breadcrumb: "System > Advanced > Group Policy Editor",
        launch_command: "gpedit.msc",
        description: "Edit local group policy settings.",
    },
    QuickAction {
        triggers: &[
            "performance monitor",
            "perfmon",
            "performance",
            "resource monitor",
            "system performance",
        ],
        name: "Performance Monitor",
        breadcrumb: "System > Diagnostics > Performance Monitor",
        launch_command: "perfmon.msc",
        description: "Monitor system performance and resource usage.",
    },
    QuickAction {
        triggers: &[
            "system restore",
            "restore point",
            "create restore",
            "system protection",
        ],
        name: "System Restore",
        breadcrumb: "System > Recovery > System Restore",
        launch_command: "rundll32.exe shell32.dll,Control_RunDLL sysdm.cpl,,4",
        description: "Configure or start System Restore.",
    },
    QuickAction {
        triggers: &[
            "system info",
            "system information",
            "sysinfo",
            "computer info",
            "about pc",
            "pc info",
        ],
        name: "System Information",
        breadcrumb: "System > Info > System Information",
        launch_command: "msinfo32.exe",
        description: "View detailed system hardware and software info.",
    },
    QuickAction {
        triggers: &[
            "disk management",
            "partition",
            "format disk",
            "manage disks",
            "volumes",
        ],
        name: "Disk Management",
        breadcrumb: "System > Storage > Disk Management",
        launch_command: "diskmgmt.msc",
        description: "Manage disk partitions and volumes.",
    },
    QuickAction {
        triggers: &[
            "task scheduler",
            "scheduled tasks",
            "schedule task",
            "auto tasks",
        ],
        name: "Task Scheduler",
        breadcrumb: "System > Scheduled > Task Scheduler",
        launch_command: "taskschd.msc",
        description: "View and manage scheduled tasks.",
    },
    QuickAction {
        triggers: &[
            "certificate manager",
            "certificates",
            "certmgr",
            "ssl certificates",
            "manage certificates",
        ],
        name: "Certificate Manager",
        breadcrumb: "System > Security > Certificate Manager",
        launch_command: "certmgr.msc",
        description: "Manage security certificates.",
    },
    QuickAction {
        triggers: &[
            "local users",
            "user management",
            "manage users",
            "lusrmgr",
            "local users and groups",
        ],
        name: "Local Users & Groups",
        breadcrumb: "System > Security > Local Users and Groups",
        launch_command: "lusrmgr.msc",
        description: "Manage local user accounts and groups.",
    },
    QuickAction {
        triggers: &["component services", "dcom", "com+ services"],
        name: "Component Services",
        breadcrumb: "System > Advanced > Component Services",
        launch_command: "comexp.msc",
        description: "Manage COM+ applications and DCOM config.",
    },
    QuickAction {
        triggers: &[
            "shared folders",
            "file sharing",
            "shared resources",
            "network shares",
            "share folders",
        ],
        name: "Shared Folders",
        breadcrumb: "System > Network > Shared Folders",
        launch_command: "fsmgmt.msc",
        description: "View and manage shared folders and sessions.",
    },
    QuickAction {
        triggers: &[
            "wifi password",
            "show wifi password",
            "wireless password",
            "network key",
            "wifi key",
        ],
        name: "Show Wi-Fi Password",
        breadcrumb: "Network > Wi-Fi > Show saved Wi-Fi passwords",
        launch_command: "action:wifi_password",
        description: "Show saved Wi-Fi network passwords.",
    },
    QuickAction {
        triggers: &[
            "kill process",
            "end process",
            "force kill",
            "kill app",
            "terminate process",
        ],
        name: "Kill Process by Name",
        breadcrumb: "System > Process > Kill a running process",
        launch_command: "action:kill_process_prompt",
        description: "Type a process name to force-kill it.",
    },
    QuickAction {
        triggers: &[
            "eject cd",
            "eject disk",
            "open tray",
            "eject dvd",
            "open cd tray",
        ],
        name: "Eject CD/DVD Tray",
        breadcrumb: "System > Hardware > Eject optical disc tray",
        launch_command: "action:eject_cd",
        description: "Eject the CD/DVD drive tray.",
    },
    QuickAction {
        triggers: &["maximize", "maximize window", "full screen window"],
        name: "Maximize Window",
        breadcrumb: "Window Management > Maximize",
        launch_command: "action:window:maximize",
        description: "Maximize the active window.",
    },
    QuickAction {
        triggers: &["restore window", "unmaximize window"],
        name: "Restore Window",
        breadcrumb: "Window Management > Restore",
        launch_command: "action:window:restore",
        description: "Restore the active window.",
    },
    QuickAction {
        triggers: &["maximize height", "tall window", "full height"],
        name: "Maximize Height",
        breadcrumb: "Window Management > Maximize Height",
        launch_command: "action:window:maximize_height",
        description: "Resize the active window to full screen height.",
    },
    QuickAction {
        triggers: &["maximize width", "wide window", "full width"],
        name: "Maximize Width",
        breadcrumb: "Window Management > Maximize Width",
        launch_command: "action:window:maximize_width",
        description: "Resize the active window to full screen width.",
    },
    QuickAction {
        triggers: &["move left", "move window left"],
        name: "Move Left",
        breadcrumb: "Window Management > Move Left",
        launch_command: "action:window:move_left",
        description: "Move the active window to the left edge.",
    },
    QuickAction {
        triggers: &["move right", "move window right"],
        name: "Move Right",
        breadcrumb: "Window Management > Move Right",
        launch_command: "action:window:move_right",
        description: "Move the active window to the right edge.",
    },
    QuickAction {
        triggers: &["center", "center window", "align center"],
        name: "Center Window",
        breadcrumb: "Window Management > Center",
        launch_command: "action:window:center",
        description: "Center the active window on screen.",
    },
    QuickAction {
        triggers: &["almost maximize", "almost maximize window"],
        name: "Almost Maximize Window",
        breadcrumb: "Window Management > Almost Maximize",
        launch_command: "action:window:almost_maximize",
        description: "Resize the active window to 95% of the screen.",
    },
    QuickAction {
        triggers: &["reasonable size", "reasonable size window"],
        name: "Reasonable Size Window",
        breadcrumb: "Window Management > Reasonable Size",
        launch_command: "action:window:reasonable_size",
        description: "Resize the active window to 70% of the screen.",
    },
    QuickAction {
        triggers: &["left half", "snap left", "tile left"],
        name: "Tile Left Half",
        breadcrumb: "Window Management > Left Half",
        launch_command: "action:window:left_half",
        description: "Tile the active window to the left half of the screen.",
    },
    QuickAction {
        triggers: &["right half", "snap right", "tile right"],
        name: "Tile Right Half",
        breadcrumb: "Window Management > Right Half",
        launch_command: "action:window:right_half",
        description: "Tile the active window to the right half of the screen.",
    },
    QuickAction {
        triggers: &["top half", "snap top", "tile top"],
        name: "Tile Top Half",
        breadcrumb: "Window Management > Top Half",
        launch_command: "action:window:top_half",
        description: "Tile the active window to the top half of the screen.",
    },
    QuickAction {
        triggers: &["bottom half", "snap bottom", "tile bottom"],
        name: "Tile Bottom Half",
        breadcrumb: "Window Management > Bottom Half",
        launch_command: "action:window:bottom_half",
        description: "Tile the active window to the bottom half of the screen.",
    },
    QuickAction {
        triggers: &["top left quarter", "snap top left", "tile top left"],
        name: "Tile Top Left Quarter",
        breadcrumb: "Window Management > Top Left Quarter",
        launch_command: "action:window:top_left_quarter",
        description: "Tile the active window to the top left quarter.",
    },
    QuickAction {
        triggers: &["top right quarter", "snap top right", "tile top right"],
        name: "Tile Top Right Quarter",
        breadcrumb: "Window Management > Top Right Quarter",
        launch_command: "action:window:top_right_quarter",
        description: "Tile the active window to the top right quarter.",
    },
    QuickAction {
        triggers: &[
            "bottom left quarter",
            "snap bottom left",
            "tile bottom left",
        ],
        name: "Tile Bottom Left Quarter",
        breadcrumb: "Window Management > Bottom Left Quarter",
        launch_command: "action:window:bottom_left_quarter",
        description: "Tile the active window to the bottom left quarter.",
    },
    QuickAction {
        triggers: &[
            "bottom right quarter",
            "snap bottom right",
            "tile bottom right",
        ],
        name: "Tile Bottom Right Quarter",
        breadcrumb: "Window Management > Bottom Right Quarter",
        launch_command: "action:window:bottom_right_quarter",
        description: "Tile the active window to the bottom right quarter.",
    },
    QuickAction {
        triggers: &["left third", "snap left third", "tile left third"],
        name: "Tile Left Third",
        breadcrumb: "Window Management > Left Third",
        launch_command: "action:window:left_third",
        description: "Tile the active window to the left third of the screen.",
    },
    QuickAction {
        triggers: &["center third", "snap center third", "tile center third"],
        name: "Tile Center Third",
        breadcrumb: "Window Management > Center Third",
        launch_command: "action:window:center_third",
        description: "Tile the active window to the center third of the screen.",
    },
    QuickAction {
        triggers: &["right third", "snap right third", "tile right third"],
        name: "Tile Right Third",
        breadcrumb: "Window Management > Right Third",
        launch_command: "action:window:right_third",
        description: "Tile the active window to the right third of the screen.",
    },
    QuickAction {
        triggers: &["left two thirds", "snap left two thirds"],
        name: "Tile Left Two Thirds",
        breadcrumb: "Window Management > Left Two Thirds",
        launch_command: "action:window:left_two_thirds",
        description: "Tile the active window to the left two thirds.",
    },
    QuickAction {
        triggers: &["right two thirds", "snap right two thirds"],
        name: "Tile Right Two Thirds",
        breadcrumb: "Window Management > Right Two Thirds",
        launch_command: "action:window:right_two_thirds",
        description: "Tile the active window to the right two thirds.",
    },
    QuickAction {
        triggers: &["make larger", "increase window size", "enlarge window"],
        name: "Make Window Larger",
        breadcrumb: "Window Management > Enlarge",
        launch_command: "action:window:make_larger",
        description: "Increase the size of the active window.",
    },
    QuickAction {
        triggers: &["make smaller", "decrease window size", "shrink window"],
        name: "Make Window Smaller",
        breadcrumb: "Window Management > Shrink",
        launch_command: "action:window:make_smaller",
        description: "Decrease the size of the active window.",
    },
    QuickAction {
        triggers: &["move top", "move window top"],
        name: "Move Top",
        breadcrumb: "Window Management > Move Top",
        launch_command: "action:window:move_top",
        description: "Move the active window to the top edge.",
    },
    QuickAction {
        triggers: &["move bottom", "move window bottom"],
        name: "Move Bottom",
        breadcrumb: "Window Management > Move Bottom",
        launch_command: "action:window:move_bottom",
        description: "Move the active window to the bottom edge.",
    },
    QuickAction {
        triggers: &["bottom center sixth"],
        name: "Bottom Center Sixth",
        breadcrumb: "Window Management > Bottom Center Sixth",
        launch_command: "action:window:bottom_center_sixth",
        description: "Tile the active window to the bottom center sixth.",
    },
    QuickAction {
        triggers: &["top center sixth"],
        name: "Top Center Sixth",
        breadcrumb: "Window Management > Top Center Sixth",
        launch_command: "action:window:top_center_sixth",
        description: "Tile the active window to the top center sixth.",
    },
    QuickAction {
        triggers: &["bottom left sixth"],
        name: "Bottom Left Sixth",
        breadcrumb: "Window Management > Bottom Left Sixth",
        launch_command: "action:window:bottom_left_sixth",
        description: "Tile the active window to the bottom left sixth.",
    },
    QuickAction {
        triggers: &["bottom right sixth"],
        name: "Bottom Right Sixth",
        breadcrumb: "Window Management > Bottom Right Sixth",
        launch_command: "action:window:bottom_right_sixth",
        description: "Tile the active window to the bottom right sixth.",
    },
    QuickAction {
        triggers: &["top left sixth"],
        name: "Top Left Sixth",
        breadcrumb: "Window Management > Top Left Sixth",
        launch_command: "action:window:top_left_sixth",
        description: "Tile the active window to the top left sixth.",
    },
    QuickAction {
        triggers: &["top right sixth"],
        name: "Top Right Sixth",
        breadcrumb: "Window Management > Top Right Sixth",
        launch_command: "action:window:top_right_sixth",
        description: "Tile the active window to the top right sixth.",
    },
    QuickAction {
        triggers: &["bottom center two thirds"],
        name: "Bottom Center Two Thirds",
        breadcrumb: "Window Management > Bottom Center Two Thirds",
        launch_command: "action:window:bottom_center_two_thirds",
        description: "Tile the active window to the bottom center two thirds.",
    },
    QuickAction {
        triggers: &["top center two thirds"],
        name: "Top Center Two Thirds",
        breadcrumb: "Window Management > Top Center Two Thirds",
        launch_command: "action:window:top_center_two_thirds",
        description: "Tile the active window to the top center two thirds.",
    },
    QuickAction {
        triggers: &["bottom third"],
        name: "Bottom Third",
        breadcrumb: "Window Management > Bottom Third",
        launch_command: "action:window:bottom_third",
        description: "Tile the active window to the bottom third.",
    },
    QuickAction {
        triggers: &["top third"],
        name: "Top Third",
        breadcrumb: "Window Management > Top Third",
        launch_command: "action:window:top_third",
        description: "Tile the active window to the top third.",
    },
    QuickAction {
        triggers: &["bottom three fourths"],
        name: "Bottom Three Fourths",
        breadcrumb: "Window Management > Bottom Three Fourths",
        launch_command: "action:window:bottom_three_fourths",
        description: "Tile the active window to the bottom three fourths.",
    },
    QuickAction {
        triggers: &["top three fourths"],
        name: "Top Three Fourths",
        breadcrumb: "Window Management > Top Three Fourths",
        launch_command: "action:window:top_three_fourths",
        description: "Tile the active window to the top three fourths.",
    },
    QuickAction {
        triggers: &["bottom two thirds"],
        name: "Bottom Two Thirds",
        breadcrumb: "Window Management > Bottom Two Thirds",
        launch_command: "action:window:bottom_two_thirds",
        description: "Tile the active window to the bottom two thirds.",
    },
    QuickAction {
        triggers: &["top two thirds"],
        name: "Top Two Thirds",
        breadcrumb: "Window Management > Top Two Thirds",
        launch_command: "action:window:top_two_thirds",
        description: "Tile the active window to the top two thirds.",
    },
    QuickAction {
        triggers: &["first fourth"],
        name: "First Fourth",
        breadcrumb: "Window Management > First Fourth",
        launch_command: "action:window:first_fourth",
        description: "Tile the active window to the first fourth.",
    },
    QuickAction {
        triggers: &["second fourth"],
        name: "Second Fourth",
        breadcrumb: "Window Management > Second Fourth",
        launch_command: "action:window:second_fourth",
        description: "Tile the active window to the second fourth.",
    },
    QuickAction {
        triggers: &["third fourth"],
        name: "Third Fourth",
        breadcrumb: "Window Management > Third Fourth",
        launch_command: "action:window:third_fourth",
        description: "Tile the active window to the third fourth.",
    },
    QuickAction {
        triggers: &["last fourth"],
        name: "Last Fourth",
        breadcrumb: "Window Management > Last Fourth",
        launch_command: "action:window:last_fourth",
        description: "Tile the active window to the last fourth.",
    },
    QuickAction {
        triggers: &["top first fourth"],
        name: "Top First Fourth",
        breadcrumb: "Window Management > Top First Fourth",
        launch_command: "action:window:top_first_fourth",
        description: "Tile the active window to the top first fourth.",
    },
    QuickAction {
        triggers: &["top second fourth"],
        name: "Top Second Fourth",
        breadcrumb: "Window Management > Top Second Fourth",
        launch_command: "action:window:top_second_fourth",
        description: "Tile the active window to the top second fourth.",
    },
    QuickAction {
        triggers: &["top third fourth"],
        name: "Top Third Fourth",
        breadcrumb: "Window Management > Top Third Fourth",
        launch_command: "action:window:top_third_fourth",
        description: "Tile the active window to the top third fourth.",
    },
    QuickAction {
        triggers: &["top last fourth"],
        name: "Top Last Fourth",
        breadcrumb: "Window Management > Top Last Fourth",
        launch_command: "action:window:top_last_fourth",
        description: "Tile the active window to the top last fourth.",
    },
    QuickAction {
        triggers: &["bottom first fourth"],
        name: "Bottom First Fourth",
        breadcrumb: "Window Management > Bottom First Fourth",
        launch_command: "action:window:bottom_first_fourth",
        description: "Tile the active window to the bottom first fourth.",
    },
    QuickAction {
        triggers: &["bottom second fourth"],
        name: "Bottom Second Fourth",
        breadcrumb: "Window Management > Bottom Second Fourth",
        launch_command: "action:window:bottom_second_fourth",
        description: "Tile the active window to the bottom second fourth.",
    },
    QuickAction {
        triggers: &["bottom third fourth"],
        name: "Bottom Third Fourth",
        breadcrumb: "Window Management > Bottom Third Fourth",
        launch_command: "action:window:bottom_third_fourth",
        description: "Tile the active window to the bottom third fourth.",
    },
    QuickAction {
        triggers: &["bottom last fourth"],
        name: "Bottom Last Fourth",
        breadcrumb: "Window Management > Bottom Last Fourth",
        launch_command: "action:window:bottom_last_fourth",
        description: "Tile the active window to the bottom last fourth.",
    },
    QuickAction {
        triggers: &["last third"],
        name: "Last Third",
        breadcrumb: "Window Management > Last Third",
        launch_command: "action:window:last_third",
        description: "Tile the active window to the last third.",
    },
    QuickAction {
        triggers: &["last three fourths"],
        name: "Last Three Fourths",
        breadcrumb: "Window Management > Last Three Fourths",
        launch_command: "action:window:last_three_fourths",
        description: "Tile the active window to the last three fourths.",
    },
    QuickAction {
        triggers: &["last two thirds"],
        name: "Last Two Thirds",
        breadcrumb: "Window Management > Last Two Thirds",
        launch_command: "action:window:last_two_thirds",
        description: "Tile the active window to the last two thirds.",
    },
    QuickAction {
        triggers: &["first third"],
        name: "First Third",
        breadcrumb: "Window Management > First Third",
        launch_command: "action:window:first_third",
        description: "Tile the active window to the first third.",
    },
    QuickAction {
        triggers: &["first three fourths"],
        name: "First Three Fourths",
        breadcrumb: "Window Management > First Three Fourths",
        launch_command: "action:window:first_three_fourths",
        description: "Tile the active window to the first three fourths.",
    },
    QuickAction {
        triggers: &["first two thirds"],
        name: "First Two Thirds",
        breadcrumb: "Window Management > First Two Thirds",
        launch_command: "action:window:first_two_thirds",
        description: "Tile the active window to the first two thirds.",
    },
    QuickAction {
        triggers: &["center half"],
        name: "Center Half",
        breadcrumb: "Window Management > Center Half",
        launch_command: "action:window:center_half",
        description: "Tile the active window to the center half.",
    },
    QuickAction {
        triggers: &["center three fourths"],
        name: "Center Three Fourths",
        breadcrumb: "Window Management > Center Three Fourths",
        launch_command: "action:window:center_three_fourths",
        description: "Tile the active window to the center three fourths.",
    },
    QuickAction {
        triggers: &["center two thirds"],
        name: "Center Two Thirds",
        breadcrumb: "Window Management > Center Two Thirds",
        launch_command: "action:window:center_two_thirds",
        description: "Tile the active window to the center two thirds.",
    },
    QuickAction {
        triggers: &[
            "toggle always on top",
            "always on top",
            "pin window",
            "pin on top",
        ],
        name: "Toggle Always on Top",
        breadcrumb: "Window Management > Always on Top",
        launch_command: "action:window:toggle_always_on_top",
        description: "Toggle whether the active window is always on top.",
    },
    QuickAction {
        triggers: &["create quicklink", "new quicklink", "add quicklink"],
        name: "Create Quicklink",
        breadcrumb: "Quicklinks > Add custom web shortcut",
        launch_command: "action:create_quicklink",
        description: "Configure a new keyword-based search engine shortcut.",
    },
    QuickAction {
        triggers: &["create snippet", "new snippet", "add snippet"],
        name: "Create Snippet",
        breadcrumb: "Snippets > Add custom text template",
        launch_command: "action:create_snippet",
        description: "Create a new text snippet template.",
    },
    QuickAction {
        triggers: &["search quicklinks"],
        name: "Search Quicklinks",
        breadcrumb: "Quicklinks > Manage and search",
        launch_command: "ql:",
        description: "Browse and search all web search shortcuts.",
    },
    QuickAction {
        triggers: &["search snippets"],
        name: "Search Snippets",
        breadcrumb: "Snippets > Manage and search",
        launch_command: "snip:",
        description: "Browse and search all text snippets.",
    },
    QuickAction {
        triggers: &["create note", "new note", "add note"],
        name: "Create Note",
        breadcrumb: "Notes > Create Note",
        launch_command: "action:create_note",
        description: "Create a new text note and open it in Notepad.",
    },
    QuickAction {
        triggers: &["search notes", "browse notes", "open notes"],
        name: "Search Notes",
        breadcrumb: "Notes > Search Notes",
        launch_command: "notes:",
        description: "Browse and search all your saved notes.",
    },
    QuickAction {
        triggers: &[
            "create focus category",
            "new focus category",
            "add focus category",
        ],
        name: "Create Focus Category",
        breadcrumb: "Focus > Add focus category",
        launch_command: "action:create_focus_category",
        description: "Create a new focus category with blocked apps.",
    },
    QuickAction {
        triggers: &["toggle focus session", "stop focus session"],
        name: "Toggle Focus Session",
        breadcrumb: "Focus > Toggle Session",
        launch_command: "action:toggle_focus_session",
        description: "Launch Windows Focus Session to toggle state.",
    },
    QuickAction {
        triggers: &["vs code new window", "vscode new window", "code new window"],
        name: "VS Code: New Window",
        breadcrumb: "Apps > VS Code",
        launch_command: "cmd /c code -n",
        description: "Open a new VS Code window.",
    },
    QuickAction {
        triggers: &["chrome incognito", "chrome private window"],
        name: "Chrome: Incognito Window",
        breadcrumb: "Apps > Chrome",
        launch_command: "cmd /c start chrome --incognito",
        description: "Open a new Chrome incognito window.",
    },
    QuickAction {
        triggers: &["ask clipboard", "ai clipboard", "chat clipboard"],
        name: "Ask Clipboard using AI",
        breadcrumb: "AI > Ask Clipboard",
        launch_command: "action:ask_clipboard",
        description: "Start an AI chat using your current clipboard text.",
    },
    QuickAction {
        triggers: &["typing practice", "monkeytype", "typing test"],
        name: "Typing Practice",
        breadcrumb: "Fun > Typing Practice",
        launch_command: "https://monkeytype.com",
        description: "Open Monkeytype in your browser.",
    },
    QuickAction {
        triggers: &["reload script commands", "refresh script commands"],
        name: "Reload Script Commands",
        breadcrumb: "Developer > Reload Script Commands",
        launch_command: "action:reload_script_commands",
        description: "Reload all script commands from disk.",
    },
    QuickAction {
        triggers: &["export snippets"],
        name: "Export Snippets",
        breadcrumb: "Snippets > Export to Desktop",
        launch_command: "action:export_snippets",
        description: "Export all snippets to snippets_export.json on your Desktop.",
    },
    QuickAction {
        triggers: &["import snippets"],
        name: "Import Snippets",
        breadcrumb: "Snippets > Import from Desktop",
        launch_command: "action:import_snippets",
        description: "Import snippets from snippets_import.json on your Desktop.",
    },
    QuickAction {
        triggers: &["export quicklinks"],
        name: "Export Quicklinks",
        breadcrumb: "Quicklinks > Export to Desktop",
        launch_command: "action:export_quicklinks",
        description: "Export all quicklinks to quicklinks_export.json on your Desktop.",
    },
    QuickAction {
        triggers: &["import quicklinks"],
        name: "Import Quicklinks",
        breadcrumb: "Quicklinks > Import from Desktop",
        launch_command: "action:import_quicklinks",
        description: "Import quicklinks from quicklinks_import.json on your Desktop.",
    },
    QuickAction {
        triggers: &[
            "mute",
            "mute sound",
            "silence pc",
            "mute volume",
            "turn off sound",
        ],
        name: "Mute Audio",
        breadcrumb: "System > Audio > Mute sound output",
        launch_command: "action:mute",
        description: "Mute the master system audio volume.",
    },
    QuickAction {
        triggers: &["unmute", "unmute sound", "unmute volume", "turn on sound"],
        name: "Unmute Audio",
        breadcrumb: "System > Audio > Unmute sound output",
        launch_command: "action:unmute",
        description: "Unmute the master system audio volume.",
    },
    QuickAction {
        triggers: &[
            "toggle hidden files",
            "show hidden files",
            "hide hidden files",
            "hidden folders",
        ],
        name: "Toggle Hidden Files",
        breadcrumb: "System > Explorer > Show or hide hidden files",
        launch_command: "action:toggle_hidden_files",
        description: "Toggle visibility of hidden files and folders in Windows Explorer.",
    },
    QuickAction {
        triggers: &["play", "pause", "play/pause", "music pause", "resume play"],
        name: "Play/Pause Media",
        breadcrumb: "System > Media > Media playback control",
        launch_command: "action:media:play_pause",
        description: "Toggle playback state of background media players.",
    },
    QuickAction {
        triggers: &["next track", "skip track", "next song", "skip song"],
        name: "Next Track",
        breadcrumb: "System > Media > Media playback control",
        launch_command: "action:media:next",
        description: "Skip to the next media track.",
    },
    QuickAction {
        triggers: &["previous track", "prev track", "previous song", "prev song"],
        name: "Previous Track",
        breadcrumb: "System > Media > Media playback control",
        launch_command: "action:media:prev",
        description: "Return to the previous media track.",
    },
    QuickAction {
        triggers: &["stop playback", "stop music", "stop video"],
        name: "Stop Playback",
        breadcrumb: "System > Media > Media playback control",
        launch_command: "action:media:stop",
        description: "Stop media playback.",
    },
    QuickAction {
        triggers: &[
            "night light",
            "nightlight",
            "blue light settings",
            "screen warmth",
        ],
        name: "Night Light Settings",
        breadcrumb: "System > Display > Night Light settings",
        launch_command: "ms-settings:nightlight",
        description: "Open the Display settings page to toggle or configure Night Light.",
    },
    QuickAction {
        triggers: &[
            "color picker",
            "colorpicker",
            "picker",
            "hex picker",
            "eye dropper",
            "eyedropper",
            "pick color",
        ],
        name: "Color Picker",
        breadcrumb: "System > GDI > Capture screen pixel color",
        launch_command: "action:color_picker",
        description: "Launch full-screen pixel color picker to copy Hex colors to clipboard.",
    },
];
